basePath: /api
definitions:
  commands.LoginCMD:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  commands.RegisterUserCMD:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  responses.LoginUserResponse:
    properties:
      access:
        type: string
      id:
        type: string
      permissions:
        items:
          type: string
        type: array
      username:
        type: string
    type: object
  responses.UserResponse:
    properties:
      id:
        type: string
      permissions:
        items:
          type: string
        type: array
      username:
        type: string
    type: object
  rest_auth.SessionResponse:
    properties:
      browser:
        type: string
      device_id:
        type: string
      ip:
        type: string
      is_blocked:
        type: boolean
      last_activity:
        type: string
      os:
        type: string
      session_id:
        type: string
      user_agent:
        type: string
      user_id:
        type: string
    type: object
host: localhost:7000
info:
  contact: {}
  title: Fiber API
  version: "1.0"
paths:
  /auth/login:
    post:
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/commands.LoginCMD'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.LoginUserResponse'
  /auth/me:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - Bearer: []
  /auth/refresh:
    patch:
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
  /auth/register:
    post:
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/commands.RegisterUserCMD'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.UserResponse'
  /auth/sessions:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/rest_auth.SessionResponse'
            type: array
      security:
      - Bearer: []
  /health:
    get:
      responses:
        "200":
          description: 'status: ok'
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - health
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and then your token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
