definitions:
  controllers.HealthResponse:
    properties:
      status:
        example: ok
        type: string
    type: object
  controllers.LogoutResponse:
    properties:
      message:
        example: Successful logout
        type: string
    type: object
  requests.RegisterUserRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  responses.CityResponse:
    properties:
      code:
        type: string
      country:
        type: string
      name:
        type: string
    type: object
  responses.LoginUserResponse:
    properties:
      access:
        type: string
      id:
        type: string
      permissions:
        items:
          type: string
        type: array
      username:
        type: string
    type: object
  responses.UserResponse:
    properties:
      id:
        type: string
      permissions:
        items:
          type: string
        type: array
      username:
        type: string
    type: object
  rest_auth.SessionResponse:
    properties:
      browser:
        type: string
      device_id:
        type: string
      ip:
        type: string
      is_blocked:
        type: boolean
      last_activity:
        type: string
      os:
        type: string
      session_id:
        type: string
      user_agent:
        type: string
      user_id:
        type: string
    type: object
  user_usecase.LoginCMD:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
host: localhost:7000
info:
  contact: {}
  title: Fiber API
  version: "1.0"
paths:
  /auth/login:
    post:
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/user_usecase.LoginCMD'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.LoginUserResponse'
      tags:
      - auth
  /auth/logout:
    post:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.LogoutResponse'
      security:
      - Bearer: []
      tags:
      - auth
  /auth/me:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.UserResponse'
      security:
      - Bearer: []
      tags:
      - auth
  /auth/refresh:
    patch:
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - Bearer: []
      tags:
      - auth
  /auth/register:
    post:
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/requests.RegisterUserRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.UserResponse'
      tags:
      - auth
  /auth/sessions:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/rest_auth.SessionResponse'
            type: array
      security:
      - Bearer: []
      tags:
      - auth
  /flight/cities:
    get:
      parameters:
      - description: name of city
        in: query
        name: q
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/responses.CityResponse'
            type: array
  /health:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.HealthResponse'
      tags:
      - health
  /users/{id}:
    get:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.UserResponse'
      security:
      - Bearer: []
      tags:
      - users
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and then your token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
